import {
  AppLayoutComponent,
  AppMenuComponent,
  AppTitleComponent,
} from './components/_layout';
import {
  SyncDetailComponent,
  NotificationSnackbar,
  LoginComponent,
  AlertSwitchingComponent,
  DashboardComponent,
  ChartStoreComponent,
  DataTabComponent,
  LoadingComponent,
  LoadingInPopupComponent,
  PunchItemComponent,
  AddPunchItemComponent,
  ImportPunchItemComponent,
  SignOffPunchItemComponent,
  EditPunchItemComponent,
  DrawingsInfoComponent,
  ProgressTabComponent,
  DirectiveProgressComponent,
  DirectivePreviewerSkylineComponent,
  DirectivePreviewerSystemComponent,
  DirectivePreviewerSubSystemComponent,
  DirectivePreviewerItrComponent,
  DirectivePreviewerPunchSComponent,
  LayoutExportedPageComponent,
  LimitsTabComponent,
  AddLimitsTabComponent,
  EditLimitsTabComponent,
  ForgotPasswordComponent,
  ResetPasswordComponent,
  PersonalInformationComponent,
  ChangePasswordComponent,
  MilestonesTabComponent,
  AddPunchWalkdownComponent,
  AnotherUserSignWalkdown,
  AnotherUserSignHandover,
  HandoverConfirmModalComponent,
  SignatureHandoverComponent,
  PreservationTabComponent,
  DetailPreservationComponent,
  ImageDetailPreservationComponent,
  SignDetailPreservationComponent,
  AnotherUserSignPreservation,
  ElementPreservationInfoComponent,
  AddDetailPreservationComponent,
  JustificationPresTabModalComponent,
  RegisterComponent,
  UserManagementComponent,
  AddUserManagementComponent,
  EditUserManagementComponent,
  ProjectManagementComponent,
  AddProjectManagementComponent,
  EditProjectManagementComponent,
  ProjectSettingsComponent,
  CompanyManagementComponent,
  AddCompanyManagementComponent,
  EditCompanyManagementComponent,
  ProjectUserComponent,
  ProjectMilestonesComponent,
  ProjectLevelsComponent,
  AddProjectUserComponent,
  EditProjectUserComponent,
  ProjectSystemComponent,
  EditProjectSystemComponent,
  AddProjectSystemComponent,
  ConditionalAcceptanceComponent,
  DataLocationComponent,
  CreateDataLocationComponent,
  EditDataLocationComponent,
  ImportDataLocationComponent,
  DataSubSystemComponent,
  CreateDataSubSystemComponent,
  EditDataSubSystemComponent,
  ImportDataSubSystemComponent,
  DataEquipmentComponent,
  CreateDataEquipmentComponent,
  EditDataEquipmentComponent,
  ImportDataEquipmentComponent,
  DataSystemComponent,
  ImportDataSystemComponent,
  CreateDataSystemComponent,
  EditDataSystemComponent,
  NotFoundComponent,
  UnauthorizeAccessComponent,
  AccessDeniedComponent,
  ActivateAccountComponent,
  NoProjectAllocatedComponent,
  DataDisciplineComponent,
  ImportDataDisciplineComponent,
  CreateDataDisciplineComponent,
  EditDataDisciplineComponent,
  DataTagNoComponent,
  CreateDataTagNoComponent,
  EditDataTagNoComponent,
  DownloadTemplateModalComponent,
  ImportDataTagDrawingComponent,
  ImportDataTagNoComponent,
  DataWorkpackComponent,
  ImportDataWorkpackComponent,
  CreateDataWorkpackComponent,
  EditDataWorkpackComponent,
  DataHandoverComponent,
  ImportHandoverComponent,
  EditHandoverComponent,
  DataJobCardComponent,
  ImportJobCardComponent,
  CreateJobCardComponent,
  EditJobCardComponent,
  DataMilestoneComponent,
  ImportDataMilestoneComponent,
  CreateDataMilestoneComponent,
  EditDataMilestoneComponent,
  DataPunchListComponent,
  ImportDataPunchListComponent,
  EditDataPunchListComponent,
  DataPunchComponent,
  ImportDataPunchComponent,
  CreateDataPunchItemComponent,
  EditDataPunchComponent,
  ITRAdminComponent,
  AddItrAdminComponent,
  EditItrAdminComponent,
  ITRAllocationComponent,
  AddItrAllocationComponent,
  EditItrAllocationComponent,
  DetailItrAllocationComponent,
  PreservationAllocationComponent,
  JustificationModalComponent,
  DetailPreservationAllocationComponent,
  DataDrawingTypeComponent,
  ImportDataDrawingTypeComponent,
  CreateDataDrawingTypeComponent,
  EditDataDrawingTypeComponent,
  DataDrawingComponent,
  ImportDataDrawingComponent,
  AddDataDrawingComponent,
  EditDataDrawingComponent,
  FileUploadComponent,
  TagTabComponent,
  AnotherUserSign,
  TagConfirmModalComponent,
  DataMaterialComponent,
  ImportDataMaterialComponent,
  EditDataMaterialComponent,
  CreateDataMaterialComponent,
  DataOrderComponent,
  ImportOrderComponent,
  EditOrderComponent,
  CreateOrderComponent,
  TagSideMenuComponent,
  EditAllocatedItrsComponent,
  JobCardsInfoComponent,
  SymbolListPopupComponent,
  FreeTextFormDataBasePopupComponent,
  FieldFromSignaturePopup,
  ITRBuilderTemplatePreviewComponent,
  ITRBuilderDetailComponent,
  ItrConfirmModalComponent,
  ITRBuilderComponent,
  DataPunchTypeComponent,
  ImportDataPunchTypeComponent,
  CreateDataPunchTypeComponent,
  EditDataPunchTypeComponent,
  DataStandardPunchItemComponent,
  ImportStandardPunchItemComponent,
  CreateStandardPunchItemComponent,
  EditStandardPunchItemComponent,
  PunchPageSetupComponent,
  ItrPageSetupComponent,
  PreservationPageSetupComponent,
  ProjectRoleComponent,
  AddProjectRoleComponent,
  CreateChangeTypeComponent,
  EditChangeTypeComponent,
  ImportChangeTypeComponent,
  DataChangeTypeComponent,
  RoleManagementComponent,
  AddRoleManagementComponent,
  EditRoleManagementComponent,
  ImportRoleComponent,
  ChangePinCodeComponent,
  ITRBuilderAnswerPopupSetting,
  ITRBuilderSignaturePopup,
  MyPunchComponent,
  AddMyPunchComponent,
  EditMyPunchComponent,
  DetailMyPunchPopupComponent,
  DetailMyPunchPageComponent,
  InitPunchComponent,
  WaitingApproveComponent,
  WaitingSignaturesComponent,
  SignaturesInfoComponent,
  AddPunchItemTagComponent,
  AllocatedITRsComponent,
  ChangePageSetupComponent,
  InitChangeComponent,
  MyChangeComponent,
  WaitingApproveChangeComponent,
  WaitingSignaturesChangeComponent,
  AddMyChangeComponent,
  EditMyChangeComponent,
  ChangeItemComponent,
  AddChangeItemComponent,
  DisciplinesInfoChangeComponent,
  ImportChangeItemComponent,
  SignOffChangeItemComponent,
  SignaturesInfoChangeComponent,
  ChangeDetailComponent,
  ChangeAttachmentsComponent,
  MilestonesPageSetupComponent,
  SystemsInfoChangeComponent,
  SubSystemsInfoChangeComponent,
  ImagesMyPunchComponent,
  NotificationsComponent,
  AllocatedInfoComponent,
  WalkdownCompleteMilestonesComponent,
  AddPartialMilestonesComponent,
  RemarksInfoComponent,
  DataPreservationElementComponent,
  ImportDataPreservationElementComponent,
  CreateDataPreservationElementComponent,
  EditDataPreservationElementComponent,
  DataRecordComponent,
  ImportDataRecordComponent,
  TagDrawingsInfoComponent,
  TagPreviewDrawingComponent,
} from './components';

export const SharedComponents = [
  //---Layouts
  AppLayoutComponent,
  AppMenuComponent,
  AppTitleComponent,

  //---Components
  SyncDetailComponent,
  NotificationSnackbar,
  LoginComponent,
  ForgotPasswordComponent,
  ResetPasswordComponent,
  RegisterComponent,

  DashboardComponent,
  LoadingComponent,
  LoadingInPopupComponent,
  ChartStoreComponent,
  AlertSwitchingComponent,

  DataTabComponent,

  DataLocationComponent,
  CreateDataLocationComponent,
  EditDataLocationComponent,
  ImportDataLocationComponent,

  DataSubSystemComponent,
  CreateDataSubSystemComponent,
  EditDataSubSystemComponent,
  ImportDataSubSystemComponent,

  DataEquipmentComponent,
  CreateDataEquipmentComponent,
  EditDataEquipmentComponent,
  ImportDataEquipmentComponent,

  DataSystemComponent,
  ImportDataSystemComponent,
  CreateDataSystemComponent,
  EditDataSystemComponent,

  PunchItemComponent,
  AddPunchItemComponent,
  ImportPunchItemComponent,
  SignOffPunchItemComponent,
  EditPunchItemComponent,
  DrawingsInfoComponent,

  ProgressTabComponent,
  DirectiveProgressComponent,
  DirectivePreviewerSkylineComponent,
  DirectivePreviewerSystemComponent,
  DirectivePreviewerSubSystemComponent,
  DirectivePreviewerItrComponent,
  DirectivePreviewerPunchSComponent,
  LayoutExportedPageComponent,

  LimitsTabComponent,
  AddLimitsTabComponent,
  EditLimitsTabComponent,

  PersonalInformationComponent,
  ChangePasswordComponent,

  MilestonesTabComponent,
  AddPunchWalkdownComponent,
  AnotherUserSignWalkdown,
  AnotherUserSignHandover,
  HandoverConfirmModalComponent,
  ConditionalAcceptanceComponent,
  AllocatedInfoComponent,
  SignatureHandoverComponent,

  PreservationTabComponent,
  DetailPreservationComponent,
  ImageDetailPreservationComponent,
  SignDetailPreservationComponent,
  AnotherUserSignPreservation,
  ElementPreservationInfoComponent,
  AddDetailPreservationComponent,
  JustificationPresTabModalComponent,

  UserManagementComponent,
  AddUserManagementComponent,
  EditUserManagementComponent,

  ProjectManagementComponent,
  AddProjectManagementComponent,
  EditProjectManagementComponent,

  ProjectSettingsComponent,

  CompanyManagementComponent,
  AddCompanyManagementComponent,
  EditCompanyManagementComponent,

  ProjectUserComponent,
  AddProjectUserComponent,
  EditProjectUserComponent,
  ProjectMilestonesComponent,
  ProjectLevelsComponent,
  ProjectSystemComponent,
  EditProjectSystemComponent,
  AddProjectSystemComponent,

  NotFoundComponent,
  UnauthorizeAccessComponent,
  AccessDeniedComponent,
  NoProjectAllocatedComponent,

  ActivateAccountComponent,

  DataDisciplineComponent,
  ImportDataDisciplineComponent,
  CreateDataDisciplineComponent,
  EditDataDisciplineComponent,

  DataTagNoComponent,
  CreateDataTagNoComponent,
  EditDataTagNoComponent,
  DownloadTemplateModalComponent,
  ImportDataTagDrawingComponent,
  ImportDataTagNoComponent,

  DataWorkpackComponent,
  ImportDataWorkpackComponent,
  CreateDataWorkpackComponent,
  EditDataWorkpackComponent,

  DataHandoverComponent,
  ImportHandoverComponent,
  EditHandoverComponent,

  DataJobCardComponent,
  ImportJobCardComponent,
  CreateJobCardComponent,
  EditJobCardComponent,

  DataMilestoneComponent,
  ImportDataMilestoneComponent,
  CreateDataMilestoneComponent,
  EditDataMilestoneComponent,
  AddPartialMilestonesComponent,
  WalkdownCompleteMilestonesComponent,

  DataPunchListComponent,
  ImportDataPunchListComponent,
  EditDataPunchListComponent,

  DataPunchComponent,
  ImportDataPunchComponent,
  CreateDataPunchItemComponent,
  EditDataPunchComponent,

  ITRAdminComponent,
  AddItrAdminComponent,
  EditItrAdminComponent,

  ITRAllocationComponent,
  AddItrAllocationComponent,
  EditItrAllocationComponent,
  DetailItrAllocationComponent,

  PreservationAllocationComponent,
  DetailPreservationAllocationComponent,
  JustificationModalComponent,

  DataDrawingTypeComponent,
  ImportDataDrawingTypeComponent,
  CreateDataDrawingTypeComponent,
  EditDataDrawingTypeComponent,

  DataDrawingComponent,
  ImportDataDrawingComponent,
  AddDataDrawingComponent,
  EditDataDrawingComponent,
  FileUploadComponent,

  TagTabComponent,
  AnotherUserSign,
  TagConfirmModalComponent,
  TagSideMenuComponent,
  EditAllocatedItrsComponent,
  JobCardsInfoComponent,

  DataMaterialComponent,
  ImportDataMaterialComponent,
  EditDataMaterialComponent,
  CreateDataMaterialComponent,

  DataOrderComponent,
  ImportOrderComponent,
  EditOrderComponent,
  CreateOrderComponent,

  SymbolListPopupComponent,
  FreeTextFormDataBasePopupComponent,
  ITRBuilderTemplatePreviewComponent,
  ITRBuilderDetailComponent,
  ItrConfirmModalComponent,
  ITRBuilderComponent,
  FieldFromSignaturePopup,

  DataPunchTypeComponent,
  ImportDataPunchTypeComponent,
  CreateDataPunchTypeComponent,
  EditDataPunchTypeComponent,
  PunchPageSetupComponent,
  ItrPageSetupComponent,
  PreservationPageSetupComponent,

  DataStandardPunchItemComponent,
  ImportStandardPunchItemComponent,
  CreateStandardPunchItemComponent,
  EditStandardPunchItemComponent,

  ProjectRoleComponent,
  AddProjectRoleComponent,

  CreateChangeTypeComponent,
  EditChangeTypeComponent,
  ImportChangeTypeComponent,
  DataChangeTypeComponent,

  RoleManagementComponent,
  AddRoleManagementComponent,
  EditRoleManagementComponent,
  ImportRoleComponent,
  ChangePinCodeComponent,
  ITRBuilderAnswerPopupSetting,
  ITRBuilderSignaturePopup,

  MyPunchComponent,
  AddMyPunchComponent,
  EditMyPunchComponent,
  DetailMyPunchPopupComponent,
  DetailMyPunchPageComponent,
  InitPunchComponent,
  WaitingApproveComponent,
  WaitingSignaturesComponent,
  SignaturesInfoComponent,
  AddPunchItemTagComponent,
  ImagesMyPunchComponent,

  AllocatedITRsComponent,

  ChangePageSetupComponent,
  MyChangeComponent,
  InitChangeComponent,
  WaitingApproveChangeComponent,
  WaitingSignaturesChangeComponent,
  AddMyChangeComponent,
  EditMyChangeComponent,
  SignaturesInfoChangeComponent,
  ChangeItemComponent,
  AddChangeItemComponent,
  DisciplinesInfoChangeComponent,
  ImportChangeItemComponent,
  SignOffChangeItemComponent,
  ChangeDetailComponent,
  ChangeAttachmentsComponent,

  MilestonesPageSetupComponent,
  SystemsInfoChangeComponent,
  SubSystemsInfoChangeComponent,

  NotificationsComponent,
  RemarksInfoComponent,

  DataPreservationElementComponent,
  ImportDataPreservationElementComponent,
  CreateDataPreservationElementComponent,
  EditDataPreservationElementComponent,

  DataRecordComponent,
  ImportDataRecordComponent,

  TagDrawingsInfoComponent,
  TagPreviewDrawingComponent,
];
